import Layout from "@/components/Layout/default";
import Stopwatch from "@/components/stopwatch";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stop Watch App | interview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Stopwatch />
        </Layout>
      </main>
    </>
  );
}
